[package]
name = "snake_game"
version = "0.1.0"
edition = "2021"
authors = ["Vincent"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# jack = "0.9.1"
sfml = "0.16.0"
rand = "0.8.0"